#!/usr/bin/env bash
set -euo pipefail

# opencode-dotfiles installer
# Installs the portable dotfiles bundle into ~/.config/opencode and ~/.agents/skills

# Usage: install.sh [--yes] [--no-deps] [--no-skills] [--force]

### Location detection
BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONFIG_DEST="${XDG_CONFIG_HOME:-$HOME/.config}/opencode"
AGENTS_SKILLS="$HOME/.agents/skills"

### Preflight checks

# Check bash version (extract major version only)
bash_version=$(bash --version | head -1 | sed 's/.*version \([0-9]\).*/\1/')
min_bash=4
if [ "$bash_version" -lt "$min_bash" ]; then
  echo "Warning: Bash $bash_version detected, version $min_bash or higher recommended"
fi

# Check set -e safety
if ! command -v tar &>/dev/null; then
  echo "Warning: tar not found, some copy operations may fall back to cp"
fi
if ! command -v cp &>/dev/null; then
  echo "Warning: cp not found, aborting"
  exit 1
fi

# Warn if opencode not on PATH (non-fatal)
if ! command -v opencode &>/dev/null; then
  echo "Warning: opencode not found on PATH (non-fatal)"
fi

### Parse arguments
YES=no
NO_DEPS=no
NO_SKILLS=kept
FORCE=no

while [[ $# -gt 0 ]]; do
  case "$1" in
    --yes)     YES=yes ;;
    --no-deps) NO_DEPS=yes ;;
    --no-skills) NO_SKILLS=skip ;;
    --force)   FORCE=yes ;;
    *) echo "Unknown option: $1" >&2 ;;
  esac
  shift
done

### Ensure config destination parent directory exists
mkdir -p "$(dirname "$CONFIG_DEST")"
mkdir -p "$CONFIG_DEST"

### Backup existing config
if [ -d "$CONFIG_DEST" ] && [ "$(ls -A "$CONFIG_DEST" 2>/dev/null | wc -l)" -gt 0 ]; then
  # Always timestamp the backup (fresh and --force runs alike)
  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
  mv "$CONFIG_DEST" "$CONFIG_DEST.bak.$TIMESTAMP"
  mkdir -p "$CONFIG_DEST"
fi

### Copy bundle content to config dest
# Exclude items that should not be copied into the config dir
EXCLUDES=(
  --exclude=node_modules
  --exclude=.git
  --exclude=env.sh
  --exclude=.env
  --exclude=.secrets
  --exclude='*.bak'
  --exclude=install.sh
  --exclude=uninstall.sh
  --exclude=README.md
  --exclude=GLOBAL-MANIFEST.md
  --exclude=LICENSE
  --exclude=skills-user
)

if command -v rsync &>/dev/null; then
  rsync -a "${EXCLUDES[@]}" "$BUNDLE_DIR"/. "$CONFIG_DEST"/
else
  # Fallback: tar pipe with excludes
  tar --exclude=node_modules --exclude=.git --exclude=env.sh --exclude=.env --exclude=.secrets \
      --exclude='*.bak' --exclude=install.sh --exclude=uninstall.sh \
      --exclude=README.md --exclude=GLOBAL-MANIFEST.md --exclude=LICENSE \
      -cf - "$BUNDLE_DIR"/. | tar -xf - -C "$CONFIG_DEST"
fi

### env.sh generation
TEMPLATE="$BUNDLE_DIR/env.sh.template"
if [ ! -f "$CONFIG_DEST/env.sh" ]; then
  cp "$TEMPLATE" "$CONFIG_DEST/env.sh"
  echo "📝 Generated $CONFIG_DEST/env.sh from template — edit placeholders for this machine"
fi

# Check template has no <CONFIG_ROOT> literals
if grep -q '<CONFIG_ROOT>' "$TEMPLATE" 2>/dev/null; then
  echo "Warning: env.sh.template contains <CONFIG_ROOT> literal — consider using placeholders"
fi

### .bashrc hook — idempotent append
BASHRC="$HOME/.bashrc"
HOOK_LINE='[ -f "$HOME/.config/opencode/env.sh" ] && . "$HOME/.config/opencode/env.sh"'
HOOK_MARKER="# opencode portable env (generated by opencode-dotfiles install)"

# Check if marker already present — idempotent
if ! grep -qF "$HOOK_MARKER" "$BASHRC" 2>/dev/null; then
  # Append the hook block
  {
    echo ""
    echo "# opencode portable env (generated by opencode-dotfiles install)"
    echo "[ -f \"\$HOME/.config/opencode/env.sh\" ] && . \"\$HOME/.config/opencode/env.sh\""
  } >> "$BASHRC"
fi

# Support zsh/fish detection even with --no-basrc spirit
if [[ "$SHELL" != */bash ]]; then
  SHELL_NAME=$(basename "$SHELL")
  if [ "$SHELL_NAME" = "zsh" ]; then
    echo "Note: zsh detected — add equivalent to ~/.zshrc:"
    echo '  [ -f "$HOME/.config/opencode/env.sh" ] && . "$HOME/.config/opencode/env.sh"'
  elif [ "$SHELL_NAME" = "fish" ]; then
    echo "Note: fish detected — add equivalent to ~/.config/fish/config.fish:"
    echo '  test -f "$HOME/.config/opencode/env.sh" and source "$HOME/.config/opencode/env.sh"'
  fi
fi

### Deps: npm install
if [ "$NO_DEPS" = "no" ]; then
  if command -v npm &>/dev/null; then
    cd "$CONFIG_DEST" 2>/dev/null || true
    npm install --ignore-scripts 2>&1 || echo "Warning: npm install had issues"
  else
    echo "Warning: npm not found — skip deps step (non-fatal)"
  fi
fi

### Skills
if [ "$NO_SKILLS" != "skip" ]; then
  mkdir -p "$AGENTS_SKILLS"
  # Copy skills-user/ to AGENTS_SKILLS, skip existing dirs unless --force
  if [ "$FORCE" = "yes" ]; then
    cp -a "$BUNDLE_DIR"/skills-user/. "$AGENTS_SKILLS"/
  else
    # Copy each skill dir, skip if exists
    for skill_dir in "$BUNDLE_DIR"/skills-user/*/; do
      [ -d "$skill_dir" ] || continue
      skill_name="$(basename "$skill_dir")"
      target_dir="$AGENTS_SKILLS/$skill_name"
      if [ -d "$target_dir" ] && [ "$FORCE" != "yes" ]; then
        # skip existing unless --force
        :
      else
        cp -a "$skill_dir" "$target_dir"
      fi
    done
  fi
  # Copy .skill-lock.json to $HOME/.agents/.skill-lock.json
  mkdir -p "$HOME/.agents"
  cp -f "$BUNDLE_DIR"/skills-user/.skill-lock.json "$HOME/.agents/.skill-lock.json"
fi

### Post-install summary
echo ""
echo "========================================="
echo "  Next steps"
echo "========================================="
echo "  Run: opencode auth login                 # re-auth; auth.json is machine-specific"
echo "  Edit:  ~/.config/opencode/env.sh         # fill OPENCODE_BIN_DIRS with machine paths"
echo "  GitHub MCP: place PAT at $CONFIG_DEST/.secrets/github-pat"
echo "  claude-mem: npx claude-mem start &"
echo "  Verify:  opencode doctor / opencode mcp lists"
echo ""

echo "Installation complete."
exit 0