#!/usr/bin/env bash
set -euo pipefail

# opencode-dotfiles uninstaller
# Removes the portable dotfiles bundle from the system

# Usage: uninstall.sh [--yes] [--keep-env]

### Location detection
BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONFIG_DEST="${XDG_CONFIG_HOME:-$HOME/.config}/opencode"
AGENTS_SKILLS="$HOME/.agents/skills"
SKILL_LOCK="$HOME/.agents/.skill-lock.json"

### Backup current config BEFORE removal
if [ -d "$CONFIG_DEST" ] && [ "$(ls -A "$CONFIG_DEST" 2>/dev/null | wc -l)" -gt 0 ]; then
  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
  mv "$CONFIG_DEST" "$CONFIG_DEST.bak.$TIMESTAMP"
fi

### Parse arguments
YES=no
KEEP_ENV=no
PURGE_SKILLS=no

while [[ $# -gt 0 ]]; do
  case "$1" in
    --yes)     YES=yes ;;
    --keep-env) KEEP_ENV=yes ;;
    --purge-skills) PURGE_SKILLS=yes ;;
    *) echo "Unknown option: $1" >&2 ;;
  esac
  shift
done

### Remove .bashrc hook block — idempotent
BASHRC="$HOME/.bashrc"
HOOK_MARKER="# opencode portable env (generated by opencode-dotfiles install)"

if [ -f "$BASHRC" ]; then
  # Remove the marker line and the following env.sh sourcing line
  TMPFILE=$(mktemp)
  skip_next=0
  while IFS= read -r line 2>/dev/null; do
    if [ "$skip_next" -eq 1 ]; then
      skip_next=0
      continue
    fi
    if [ "$line" = "$HOOK_MARKER" ]; then
      skip_next=1
      continue
    fi
    echo "$line"
  done < "$BASHRC" > "$TMPFILE"
  mv "$TMPFILE" "$BASHRC"
fi

### Remove config dest
if [ "$KEEP_ENV" != "yes" ]; then
  # Remove $CONFIG_DEST entirely BEFORE any other removal
  rm -rf "$CONFIG_DEST"
fi

### Skills handling — do NOT delete user skills by default
if [ "$PURGE_SKILLS" = "yes" ] && [ "$YES" = "yes" ]; then
  # Both --yes and --purge-skills: remove user skills entirely
  rm -rf "$AGENTS_SKILLS"
  echo "Note: User skills at $AGENTS_SKILLS removed (--purge-skills used)."
else
  # Default: keep user skills intact
  if [ -d "$AGENTS_SKILLS" ]; then
    echo "Note: User skills at $AGENTS_SKILLS are kept intact."
  fi
  # Always keep .skill-lock.json — it tracks user skills
  if [ -f "$SKILL_LOCK" ]; then
    echo "Note: $SKILL_LOCK kept (tracks user skills)."
  fi
fi

### Restore instructions
echo ""
echo "========================================="
echo "  Uninstall complete"
echo "========================================="
echo "  Config backed up to .bak.<timestamp>"
echo "  To restore: mv $CONFIG_DEST.bak.<timestamp> $CONFIG_DEST"
echo "  User skills at $AGENTS_SKILLS are intact unless --yes --purge-skills was used"
echo "  If --keep-env was used, env.sh is preserved in the backup"
echo ""

exit 0